---
# tasks file for ghobadimhd.opendkim


- name: Load distribuion specific variabales
  include_vars: "vars/{{ ansible_os_family }}.yml"

- name: Add repository
  yum_repository:
    name: epel
    state: present
    description: EPEL YUM repo
    mirrorlist: https://admin.fedoraproject.org/mirrormanager/mirrors/EPEL/$releasever/$basearch
  when: ansible_os_family == 'RedHat'

- name: install opendkim
  package:
    state: present
    name: "{{ packages }}"

- name:
  user:
    name: "{{ opendkim_user }}"
    state: present
    home: "/var/run/{{ opendkim_user }}"
    shell: /bin/false

- name: create opendkim directory
  file:
    path: /etc/opendkim/
    state: directory
    owner: opendkim
    group: root

- name: create key directory
  file:
    path: "{{ opendkim_keypath }}"
    state: directory
    owner: opendkim
    group: root

- name: config opendkim
  template:
    src: "opendkim.conf"
    dest: "{{ opendkim_config_file }}"
    owner: opendkim
    group: opendkim
  notify:
    - restart opendkim
    # - restart postfixs

- name: config opendkim socket
  template:
    src: "default_opendkim"
    dest: "/etc/default/opendkim"
    owner: opendkim
    group: opendkim
  notify:
    - restart opendkim
    # - restart postfix

- name: Create key table file
  template:
    src: keytable.j2
    dest: "{{ opendkim_keyTable }}"
    owner: opendkim
    group: opendkim

- name: Create signing table file
  template:
    src: signingtable.j2
    dest: "{{ opendkim_signingTable }}"
    owner: opendkim
    group: opendkim


- name: generating opendkim keys
  include_tasks: opendkim-genkeys.yml
  with_items: "{{ opendkim_domains }}"




